### ISSUE TITLE
[Bug]: False positive due to version numbers

### ISSUE THREAD

**Issue by zbalkan** [jdhitsolutions/WingetTools#20]
### Describe the problem

Comparing versions of software using semver schema is always hard. Here we came across a false positive. It is not a big issue other than an inconvenience and the effort might not worth it.

## Prequisite
Have Wireshark installed.

## Steps
1. Run `Get-WGUpgrade | Out-GridView -OutputMode Multiple | Invoke-WGUpgrade`
2. You will see the result below:

![image](https://user-images.githubusercontent.com/39981909/210400946-e65748dc-24d3-499f-a324-1b7e98d73ebf.png)

3. Check the source of `Get-WinGetUpgrade.ps1`, and find the line which enumerates and checks updates
4. Try the code separately.
```powershell
# $list = Get-WGInstalled | Where-Object {$_.Update -And ($_.InstalledVersion)}
# $list.OnlineVersion
4.0.2.0
# $list.InstalledVersion
4.0.2
```
5. See that the code cannot handle semver version numbers.

### Expectation

Should return no updates.

### Additional Information

winget version: v1.3.2691
WingetTools version: 1.7.0

### PowerShell version

7.2

### Platform

Windows 10 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [X] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
I've seen this as well. Another limitation of trying to parse text from Winget's output. This is especially difficult when you get a version number like `1.2.0.1165.gabf054ab`.

**Comment by jdhitsolutions** [comment]
Parsing strings consistently is a non-starter. The microsoft.winget.client module from Microsoft will eventually replace this module.
