### ISSUE TITLE
[Bug]: Get-WGPackage does not return all the object properties

### ISSUE THREAD

**Issue by MitushYadav** [jdhitsolutions/WingetTools#5]
### Describe the problem

Running `Get-WGPackage -id 'putty.putty' ` returns

Name             : PuTTY
ID               : PuTTY.PuTTY
Version          :
Publisher        :
PublisherURL     :
PublisherSupport :
Author           :
Moniker          :
Description      :
Homepage         :

### Expectation

The command should return more details.

### Additional Information

winget v1.2.10271

I looked into the private.ps1 and these could be the potential fixes:
1. functions\private.ps1
 $value = $find.split("$($key):")[1].trim() => $value = $($find -split "$($key):")[1].trim()

2. The string for Publisher Url do not match:
PublisherURL  => Publisher Url
PublisherSupport => Publisher Support Url
reference: [winget-pkgs](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.1.0/defaultLocale.md)

### PowerShell version

5.1

### Platform

Windows 10 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [ ] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
One of the challenges of using regex is that you expect output the be consistent. Sometimes it isn't. Let me see what I can do.,

**Comment by jdhitsolutions** [comment]
The first time I tried the command I got the same results you did. But when I ran it again, it worked.

![image](https://user-images.githubusercontent.com/12089920/162826279-80d62b52-6d02-4887-9203-a7bcd04b5c9e.png)

Not every package provides all details but this looks like it is working. The first time you run `winget` after some unknown period of time, It writes other output which I thought I had accounted for. I hadn't used winget in several days so initially got your result. But running it a second time and everything worked.

**Comment by jdhitsolutions** [comment]
But I can see now that publisher info isn't properly parsing.

**Comment by jdhitsolutions** [comment]
I had something else in mind for parsing out the publisher data but apparently, I didn't think it all the way through. Working on an update that should work.

**Comment by jdhitsolutions** [comment]
Update the module to v1.3.0 and see if it works better for you.

**Comment by MitushYadav** [comment]
Updated to v1.3.0 and I get the required output. Thanks!
