### ISSUE TITLE
[Request]: Invoke-WGUpgrade -all /full 

### ISSUE THREAD

**Issue by necrose99** [jdhitsolutions/WingetTools#6]
### Describe the request

Invoke-WGUpgrade -all / >>` winget upgrade --all `

**Invoke-WGUpgrade  --full**   /`winget upgrade --all "--include-unknown" `

one-line upgrade everything could be useful esp on scheduled tasks 

### PowerShell version

7.2

### Platform

Windows 10 Pro or Enterprise

**Comment by jdhitsolutions** [comment]
I guess I don't see a problem with this approach. The `-Full` parameter may have to be dynamic since `--include-unknown` looks like a recent addition to winget.

**Comment by jdhitsolutions** [comment]
I've published version 1.4.0 to the PowerShell Gallery with updates to `Invoke`WGUpgrade`.
